// Screenshot page 1 of the sample CV (built by cv-html.gen.ts from the product's own renderer) as a PNG for the film.
import fs from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { chromium } from "@playwright/test";

const root = path.resolve(import.meta.dirname, "../..");
const FONTS = [
  ["Spectral", 500, "spectral-latin-500-normal.woff2"],
  ["Spectral", 600, "spectral-latin-600-normal.woff2"],
  ["Barlow", 400, "barlow-latin-400-normal.woff2"],
  ["Barlow", 500, "barlow-latin-500-normal.woff2"],
  ["Barlow", 600, "barlow-latin-600-normal.woff2"],
];
const css = FONTS.map(([f, w, file]) => {
  const b64 = fs.readFileSync(path.join(root, "lib/cv/fonts", file)).toString("base64");
  return `@font-face{font-family:"${f}";font-weight:${w};font-style:normal;src:url(data:font/woff2;base64,${b64}) format("woff2")}`;
}).join("");

const html = fs.readFileSync(path.join(root, "pitch/assets/cv.html"), "utf8").replace("<style>", `<style>${css}`);
const browser = await chromium.launch({ executablePath: process.env.PW_CHROMIUM_PATH || undefined });
const page = await browser.newPage({ viewport: { width: 794, height: 1123 }, deviceScaleFactor: 3 });
await page.setContent(html);
await page.addStyleTag({ content: "body{padding:56px 60px 0;box-sizing:border-box;width:794px}" });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: path.join(root, "pitch/assets/cv.png"), clip: { x: 0, y: 0, width: 794, height: 1123 } });
await page.locator(".cv-foot").screenshot({ path: path.join(root, "pitch/assets/cv-foot.png") });

// A real PDF of the sample CV, its real SHA-256, and the real SHA-256 after flipping one byte.
const pdf = await page.pdf({ format: "A4", printBackground: true, margin: { top: "18mm", bottom: "18mm", left: "16mm", right: "16mm" } });
const FLIP = 7;
const altered = Buffer.from(pdf);
altered[FLIP] = altered[FLIP] ^ 0x01;
const sha = (b) => createHash("sha256").update(b).digest("hex");
const facts = {
  file: "ayesha-khan-cv.pdf",
  size: pdf.length,
  flipIndex: FLIP,
  bytes: [...pdf.subarray(0, 16)].map((b) => b.toString(16).padStart(2, "0")),
  flippedByte: altered[FLIP].toString(16).padStart(2, "0"),
  hash: sha(pdf),
  alteredHash: sha(altered),
};
fs.writeFileSync(path.join(root, "pitch/assets/cv-facts.js"), `// Generated by scripts/capture-cv.mjs from a real PDF of the sample CV.\nexport const CV_FACTS = ${JSON.stringify(facts, null, 2)};\n`);
console.log(facts.size, "bytes", facts.hash.slice(0, 16), facts.alteredHash.slice(0, 16));
await browser.close();
console.log("wrote pitch/assets/cv.png, cv-foot.png");
